# Generated by Django 3.2.3 on 2021-05-31 18:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CommunicationType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('communication_name', models.CharField(max_length=80)),
            ],
        ),
        migrations.CreateModel(
            name='Component',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('component_name', models.CharField(max_length=80)),
                ('parent_component', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.component')),
            ],
        ),
        migrations.CreateModel(
            name='DataAcquisitionModule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('installation_date', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='DataAcquisitionModuleType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dam_name', models.CharField(max_length=80)),
            ],
        ),
        migrations.CreateModel(
            name='SensorType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
            ],
        ),
        migrations.CreateModel(
            name='SensorModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_name', models.CharField(max_length=80)),
                ('communication_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.communicationtype')),
                ('sensor_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.sensortype')),
            ],
        ),
        migrations.CreateModel(
            name='SensorImplementation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('component', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.component')),
                ('dam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.dataacquisitionmodule')),
                ('sensor_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.sensormodel')),
            ],
        ),
        migrations.CreateModel(
            name='RequiredPin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pin_name', models.CharField(max_length=80)),
                ('communication_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.communicationtype')),
            ],
        ),
        migrations.CreateModel(
            name='PinUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigned_pin', models.CharField(max_length=20)),
                ('required_pin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.requiredpin')),
                ('sensor_implementation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.sensorimplementation')),
            ],
        ),
        migrations.CreateModel(
            name='MeasuredVariable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('variable_name', models.CharField(max_length=80)),
                ('unit', models.CharField(max_length=80)),
                ('sensor_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.sensormodel')),
            ],
        ),
        migrations.AddField(
            model_name='dataacquisitionmodule',
            name='dam_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.dataacquisitionmoduletype'),
        ),
        migrations.AddField(
            model_name='dataacquisitionmodule',
            name='sensors',
            field=models.ManyToManyField(through='main.SensorImplementation', to='main.SensorModel'),
        ),
    ]
