# Generated by Django 3.2.3 on 2021-06-07 09:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_component_parent_component'),
    ]

    operations = [
        migrations.AlterField(
            model_name='component',
            name='parent_component',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.component'),
        ),
    ]
