# Generated by Django 3.2.3 on 2021-06-07 10:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_component_parent_component'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pinusage',
            name='required_pin',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='main.requiredpin'),
        ),
    ]
