# Generated by Django 3.2.3 on 2021-06-15 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20210607_1502'),
    ]

    operations = [
        migrations.AddField(
            model_name='sensorimplementation',
            name='measured_unit',
            field=models.CharField(blank=True, default='', max_length=80),
        ),
        migrations.AddField(
            model_name='sensorimplementation',
            name='measured_variable',
            field=models.CharField(blank=True, default='', max_length=80),
        ),
        migrations.DeleteModel(
            name='MeasuredVariable',
        ),
    ]
