# Generated by Django 3.2.3 on 2021-06-15 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_auto_20210615_1403'),
    ]

    operations = [
        migrations.AddField(
            model_name='sensorimplementation',
            name='cycle_time',
            field=models.IntegerField(default=1000),
        ),
    ]
